### ISSUE TITLE
Multiplayer Functionality

### ISSUE THREAD

**Issue by Fullmetalgaz** [thomasweston12/SometimesFriendsFight#33]
At this point, multiple player prefabs exist in the level and can be referenced in the menus and player manager but the controls for player 2 that i found while testing combat don't work correctly. The player will be moving in a direction very slowly and both thumbsticks on the controller do other actions. The right thumbstick is inverted to look up and down and the left moving the camera left and right. The first player moves just fine but the pick up action can't work correctly as it's based off of the camera that is now on player 2. 

https://answers.unity.com/questions/1293382/instance-a-scene-twice-two-worlds-two-cameras-etc.html

Above is a link to a suggestion on the unity forums on how to set split screen up. Once this is in there, the raycasts should work fine but we can't push forward with other things until this is sorted.

**Comment by thomasweston12** [comment]
Pickup action now fixed as of the latest commit, raycasts and crosshairs now moved to the player's cameras rather than the center of the screen. The movement bugs will just be tweaking the player 2, 3, and 4 controller inputs to match player 1's

**Comment by thomasweston12** [comment]
Bug Fixed: Had to change the input manager values for players 2, 3, and 4, as player 1's had been changed prior to multiplayer being implemented, however the other players hadn't.
